services:
  backend:
    build:
      context: ./backend/
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend/
    ports:
      - '8080:80'
